parse_input:
  name: parse_input
  description: >
    Parse the raw input:
    - conf/Journal: {conf}
    - author: {author}
    - problem_statement: {problem_statement}
    - proposal: {proposal}
    - contributions: {contributions}
    - results: {results}
    - title (optional): {title}
    - abstract (optional): {abstract}
    - keywords (optional): {keywords}
    - images (optional): {images}
    - sources/citations/references (optional): {references}
    Extract only relevant, structured information and discard any irrelevant or mixed content. Ignore empty optional fields
  expected_output: >
    A structured JSON or YAML object containing those fields, using null for missing.
  agent: planner
  markdown: false
  async_execution: false